### ISSUE TITLE
write to RDFstream instead of to in-memory RDF model

### ISSUE THREAD

**Issue by pipauwel** [mmlab/IFC-to-RDF-converter#10]
In-memory model takes too much memory -> stream in, stream out needed

https://github.com/mmlab/IFC-to-RDF-converter/blob/BS/converter/src/org/buildingsmart/IfcConvertor.java
--> createInstances()

you can create Triple objects (OntResource.asNode() / Triple constructor) and send these to the StreamWriter in Jena
In that case, you don't use an in memory model
but there should not be too many dependencies between objects

StreamRDF writer = StreamRDFWriter.getWriterStream(outputStream, RDFFormat.TURTLE) ;
writer.prefix(prefix,namespace);
[start for loop]
writer.start();
writer.triple({insert Triple here});
writer.finish()
[end for loop]

**Comment by jyrkio** [comment]
Since the StreamRDF  streaming writing differ quite a lot from the original RDF generation, new classes IfcReaderStream and IfcConvertorStream were created. These does write Turtle only and there is no validation at least yet.  Jena libraries were updated to the newest one.
