### ISSUE TITLE
remove duplicate literal values

### ISSUE THREAD

**Issue by pipauwel** [mmlab/IFC-to-RDF-converter#9]
When building an RDF model of any incoming IFC file, literal values are converted into duplicate owl:class instances. See below for an example. These duplicates should be removed whenever possible to decrease file size and model size.

inst:IfcLengthMeasure_127
        a                  ifcowl:IfcLengthMeasure ;
        ifcowl:has_double  "0."^^<http://www.w3.org/2001/XMLSchema#double> .

inst:IfcLengthMeasure_156
        a                  ifcowl:IfcLengthMeasure ;
        ifcowl:has_double  "0."^^<http://www.w3.org/2001/XMLSchema#double> .

**Comment by jyrkio** [comment]
IfcConvertor.resource_map was created to handle these. The change seems to be OK. Validation was passed OK. generated RDF graph is OK! Writing TTL and RDF file...
